insert into author (author_id, `name`) values (1, 'Leo Tolstoy');
insert into author (author_id, `name`) values (2, 'Chuck Palahniuk');
insert into author (author_id, `name`) values (3, 'Harper Lee');
insert into author (author_id, `name`) values (4, 'Daniel Keyes');
insert into author (author_id, `name`) values (5, 'Алексей Пехов');
insert into author (author_id, `name`) values (6, 'Наталья Турчанинова');
insert into author (author_id, `name`) values (7, 'Елена бычкова');
insert into book (book_id, `name`, author_id) values (1, 'War and Peace', 1);
insert into book (book_id, `name`, author_id) values (2, 'Fight Club', 2);
insert into book (book_id, `name`, author_id) values (3, 'To Kill a Mockingbird', 3);
insert into book (book_id, `name`, author_id) values (4, 'Flowers for Algernon', 4);
insert into book (book_id, `name`, author_id) values (5, 'Anna Karenina', 1);
insert into book (book_id, `name`, author_id) values (6, 'Childhood', 1);
insert into book (book_id, `name`, author_id) values (7, 'Boyhood', 1);
insert into book (book_id, `name`, author_id) values (8, 'Пересмешник', 5);
insert into book (book_id, `name`, author_id) values (9, 'Пересмешник', 6);
insert into book (book_id, `name`, author_id) values (10, 'Пересмешник', 7);